service: serverless-cloudwatch-subscription

provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-pseudo-parameters
  - serverless-plugin-log-subscription

custom:
  logSubscription:
    enabled: true
    roleArn:
      Fn::GetAtt:
        - KinesisStreamIAMRole
        - Arn
    destinationArn:
      Fn::GetAtt:
        - LoggingStream
        - Arn

functions:
  ship:
    handler: functions/logging/ship.handler
    timeout: 10
    logSubscription: false
    events:
      - stream:
          type: kinesis
          batchSize: 3
          startingPosition: TRIM_HORIZON
          enabled: true
          arn:
            Fn::GetAtt:
              - LoggingStream
              - Arn
    environment:
      ELASTICSEARCH_URL: "https://search-my-test-domain-tfdshojp63lnfe7cv372n35qoa.us-east-1.es.amazonaws.com"
  testing:
    handler: functions/testing/index.handler

resources:
  Resources:
    LoggingStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: Logging
        ShardCount: 1
    KinesisStreamIAMRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: 'KinesisAnalyticsAssumeRole'
              Effect: Allow
              Principal:
                Service: logs.#{AWS::Region}.amazonaws.com
              Action: 'sts:AssumeRole'
        Policies:
          - PolicyName: kinesis-stream-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: "Allow"
                  Action:
                    - "kinesis:DescribeStream"
                    - "kinesis:PutRecord"
                    - "kinesis:PutRecords"
                  Resource:
                    'Fn::GetAtt':
                      - LoggingStream
                      - Arn
